### ISSUE TITLE
Doesn't play nice with PhantomJS

### ISSUE THREAD

**Issue by mrenty** [callmecavs/jump.js#10]
My tests throw an error when running in PhantomJS, it doesn't recognise Window.requestAnimationFrame().

**Comment by callmecavs** [comment]
`window.requestAnimationFrame()` is a [real thing](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), i promise. because Phantom runs a headless Webkit browser, perhaps the unprefixed version isn't supported?

you could try adding a shim - which would detect browser specific versions - or a polyfill. see [here](http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/). beyond that, I can't be of much help.

closing this as it's related to Phantom, not an issue with the library itself. do let me know if the above works though. best of luck :beers:

**Comment by mrenty** [comment]
Yeah you're right this isn't an issue with Jump but I was wondering if you already encountered this and found a solution for this. Will try it and will let you know 👍

**Comment by callmecavs** [comment]
please do, because in the future, if I'd like to write tests for this, I'd probably end up doing so using Phantom JS haha. thanks for your understanding
