### ISSUE TITLE
Undefined versions in package.json

### ISSUE THREAD

**Issue by iduuck** [callmecavs/jump.js#14]
I was just curious why there are all versions defined with a astericks. Don't know if this has a specific reason. But I think the dependency management should be controlled by the `package.json`?

**Comment by callmecavs** [comment]
the library is dependency free.

the only dependencies listed in the `package.json` are `devDependencies` -  build tools such as Gulp, browserify, etc. typically I dont version them because I like to ensure all the build tools are the latest versions, and because their versioning doesn't effect the functionality of the library. nonetheless, I appreciate you raising the issue, and i'll put some thought into locking them in.

**Comment by iduuck** [comment]
Just to note this here: I am currently experiencing issues because of the new
version of `babel` and `gulp`. So it's telling me the following error:

```
Failed to load external module babel/register  
```

**Comment by callmecavs** [comment]
interesting, i'll look into it

**Comment by iduuck** [comment]
Did some research and found a feasible answer. Some issues on the `gulp` repository are referring to `babel-core` that needs to be used since babel version `6.0.0`.

So I just updated my gulp-cli with `npm install -g gulp` and it was searching for `babel-core/register` and not `babel/register` anymore.

(That's the problem with the astericks as version)

I will do a pull request with the versions that are working for me. Feel free to merge or comment on it.

Further reading: https://github.com/gulpjs/gulp/issues/1364
