### ISSUE TITLE
Serve non-minified version of jump.js

### ISSUE THREAD

**Issue by saarons** [callmecavs/jump.js#26]
I get the following error in my application when using jump.js with Webpack. Since most people are doing minimization anyways later in their compilation pipelines, shouldn't jump.js try to serve a non-minified file? It would be just one change in the gulpfile I think.

```
WARNING in ./~/jump.js/dist/jump.min.js
Critical dependencies:
6:406-413 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/jump.js/dist/jump.min.js 6:406-413
```

**Comment by vincentorback** [comment]
I’m just taking a wild guess the `"main": "dist/jump.min.js"` in the `package.json` is what’s npm is using to decide which file to use? I vote +1 to change it to the non-minified file.

**Comment by saarons** [comment]
Correct, that's what npm is using to decide on the minified file. I think this requires a small code change to change the build script to not minify, but I'm not 100% sure.

**Comment by callmecavs** [comment]
@vincentorback @saarons makes sense, since people using this from NPM must be using a module bundler and are likely minifying their build anyways. I want to support ES6 practices and workflow above all else, and I think this suggestion is in line with that.

the relevant line of the `gulpfile` is [here](https://github.com/callmecavs/jump.js/blob/master/gulpfile.babel.js#L60). removing that will keep the `dist` file from being minified. if it's not minified, it would also be wise to rename it, removing the `.min`.

this weekend, i'm planning on un-minifying all my `dist` files, for all my libraries, as well as adding the `jsnext:main` field to all my `package.json`s, to support future-facing tree-shaking module bundlers like [rollup](https://github.com/rollup/rollup)

**Comment by cattermo** [comment]
Will this be implemented any time soon?

**Comment by ghost** [comment]
For those waiting, Sitepoint offers a ES5 version in an article about this lib. Don't know the diff to the last version, but seems to work and includes an accessibility bugfix as a bonus. http://www.sitepoint.com/smooth-scrolling-vanilla-javascript/

(Note: I'm not affiliated with them, just thought it is worth pointing out while this case is open)

**Comment by callmecavs** [comment]
please see #31, and leave your feedback!
