### ISSUE TITLE
Instantiate necessary? (API change suggestion)

### ISSUE THREAD

**Issue by electerious** [callmecavs/jump.js#28]
Hi,

I'm wondering why it's necessary to instantiate jump.js. It looks like this instance holds no decided information and there's no way to pass options to it. Instances are normally uses to hold data, which doesn't seems to be the case here. I think the API would be much simpler and cleaner when we could use jump directly:

``` js
// import Jump
import Jump from 'jump.js'

Jump('.selector', {
  // options...
})
```

Great work anyway!

**Comment by electerious** [comment]
I think using `class` might not be the best choice here. You could export the main function directly.

Let me know if this is a welcome change, so I can take a closer look at it and open a PR.

**Comment by mgiulio** [comment]
100% agree.
I have an article on Sitepoint in peer-review stage about smooth scrolling where I present a modified/refactored(that is, the core animation code is the same) version of Jump.js, and the above two suggestions by @electerious are two of the applied customizations.
Just my 0.02€,
mg

**Comment by callmecavs** [comment]
@electerious @mgiulio you're both correct imo. all the options have sensible defaults, except the target and duration, which I'm fine with being required. I've been planning on a v1.0.0 release that removes the `class` structure, and uses the revealing module pattern, similar to my libraries I've updated/released recently. I'm certainly open to a pull request accommodating this change if either of you are up to it. otherwise, I plan on getting around to it soon.

@mgiulio also super interested in the sitepoint article! happy to see people referencing, analyzing, and otherwise thinking about my code. let me know if you have any questions, or would like to co-author something. cheers :beers:

**Comment by mgiulio** [comment]
Hi @callmecavs , sorry for the late reply.

I'm too busy for a PR now but I could send you the draft, so you can see my code changes and review the article. Just let me know.

mg

**Comment by mgiulio** [comment]
Hi @callmecavs, the article is [out](http://www.sitepoint.com/smooth-scrolling-vanilla-javascript/) !

**Comment by callmecavs** [comment]
please see #31

**Comment by callmecavs** [comment]
also, @mgiulio - as i said [on](https://twitter.com/callmecavs/status/729720364184506368) [Twitter](https://twitter.com/callmecavs/status/729717792749064192) - fantastic article. really well written, and I appreciate you analyzing and writing about my work. please let me know what you'd like to see in v1.0.0!

**Comment by mgiulio** [comment]
@callmecavs Glad you liked it!

Looking forward to v1.0.0.

I appreciate your efforts to revisit common UX patterns with vanilla JavaScript solutions. I've also enjoyed [Layzr](https://github.com/callmecavs/layzr.js).

**Comment by callmecavs** [comment]
@mgiulio much appreciated sir.

i follow the "3 strikes rule" - write the same code 3 times, on 3 different websites, and it should probably be an open source library. common UX patterns typically fall into this category - relevant and needed on every site (way more than 3)

everything i make comes about because of that rule and/or frustration with current libraries that address the problem im trying to solve. i appreciate all the support my libraries have gotten, and contributions from people like yourself.

This library (Jump) is actually my most depended on according to [npm stats](http://www.npm-stats.com/callmecavs). so its only right i gather feedback from the community, and launch a proper v1.0.0, that incorporates what people want/need
