### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by controversial** [callmecavs/jump.js#45]
Is there a CDN-hosted copy of this library? With almost 2.5k stars, it seems like there should be...

**Comment by controversial** [comment]
I got jump.js added to cdnjs [here](https://cdnjs.com/libraries/jump.js)

**Comment by callmecavs** [comment]
thanks @controversial. following the lead of libraries like lodash, I'm trying to encourage people to consume the script using npm and a module bundling build step, rather than `<script>` tags and CDNs, but i appreciate the initiative.

btw, check out [unpkg](https://unpkg.com/#/) btw - it provides a CDN link for all packages on npm, pretty sweet

**Comment by controversial** [comment]
Ok, thanks! I'll look into that.
