### ISSUE TITLE
Rollup preset (in .babelrc) crashes Webpack builds

### ISSUE THREAD

**Issue by MilllerTime** [callmecavs/jump.js#46]
Thanks for the elegant library! It does a wonderful job.

One issue: I can't bundle the jump.js module as-is. I'm using webpack and babel, and getting the following error:

```
ERROR in ./~/jump.js/src/jump.js
Module build failed: Error: Couldn't find preset "es2015-rollup" relative to directory
"...\\node_modules\\jump.js"
```

The issue seems to be that my instance of babel sees your `.babelrc` file and tries to bundle your code using the rollup preset, which I don't have installed. If I delete your `.babelrc`, it compiles flawlessly.

Any chance the babel config could be inlined in the `.gulpfile` so it only applies to isolated builds of jump.js? Or perhaps there is a better method of handling this sorta thing - I'm no pro when it comes to open-source bundler-agnostic transpiled npm modules.

**Comment by dbartel** [comment]
Ran into this problem on something I was working on, turned out to be not too painful to fix. Made a pull request here #47

**Comment by MilllerTime** [comment]
Looks excellent @dbartel! I didn't know babel config could live in package.json - good to know. I definitely appreciate the effort, hopefully it can be merged soon 👍

**Comment by dbartel** [comment]
@MilllerTime turns out you also need to move es2015-rollup out of devDependencies to dependencies in package.json for npm to build this correctly - I had tested this just by copying the built file over instead of pulling it down from npm - the latest commit I pushed will fix this

If you need to use this change, you can pull down a specific commit for an npm module like this:

``` json
{
     "jump.js": "dbartel/jump.js#5a41ea2f9b5caaab4e958b19a0a4e30bf9386d61"
}
```

Keep in mind this locks you to this specific forked off commit, so moving to an updated jump.js in the future could be a hassle.

**Comment by MilllerTime** [comment]
Hmm. So now any user installing jump.js will have `es2015-rollup` added to their `package.json`? If rollup is only needed to build the project, it seems like a nonessential dependency. I'm able to compile the jump.js module as a part of my project without rollup, alternatively using webpack. I don't really want rollup to be included in my dependencies just because of this library. Is there a way to avoid the errors I showed above, while keeping `es2015-rollup` as a devDependency?

Edit:
For example, babel-loader for webpack allows specifying config inline via the `query` property: https://github.com/babel/babel-loader#usage. If something like this exists for rollup (my searching turned up nothing), it seems to me that it would resolve the issue.

**Comment by callmecavs** [comment]
@MilllerTime @dbartel ill address this sooner rather than later - in the midst of reworking the build system of my projects to use webpack2 instead of rollup.  Rollups treeshaking and scope collapsing will be coming to webpack2 soon - these differences were the reason I originally chose it over webpack.

Thank you both for your patience, and for hashing out a fix here and in the PR. will update and close this issue when I've made the changes.

**Comment by callmecavs** [comment]
@MilllerTime @dbartel updated the dist files in the latest release - shouldn't be any problems with imports anymore. sorry this took so long

**Comment by MilllerTime** [comment]
Awesome, no more errors here. Thank you for resolving this!

**Comment by callmecavs** [comment]
@MilllerTime no problemo, thanks for confirming the fix. sorry it took me forever.
