### ISSUE TITLE
Import in Angular 2 fails. "Cannot find module"

### ISSUE THREAD

**Issue by danfri86** [callmecavs/jump.js#49]
I'm trying to use jump.js in my Angular 2 app. The scrolling actually works but I get an error from my IDE saying "Cannot find module 'jump'".

I'm installing with node `$ npm install jump.js --save-dev`.

In my system.config.js:
```
var map = {
    'jump': 'node_modules/jump.js/dist/jump.min.js'
};

var packages = {
    'jump': { defaultExtension: 'js' }
}

System.config({
    map: map,
    packages: packages
  });
```

I'm then importing in my component with `import jump from 'jump';`and I've also tried `import * as jump from 'jump';`.

Since I get an error I can't compile AoT since it catches the error. Any solution?
Thank you.

**Comment by austindebruyn** [comment]
@danfri86 `import jump from 'jump.js';`?

**Comment by callmecavs** [comment]
@danfri86 @austindebruyn updated the `dist` files in the latest release (v1.0.2) - assuming the lib is imported correctly (as in the comment above) any errors should be gone.

**Comment by nickthakkar** [comment]
@callmecavs tried exactly what you are suggesting. But using` import jump from 'jump.js';` simply won't work since he has word 'jump' in his system js mapping. I have followed its Readme but that did not help me fixing this issue.  I will appreciate if you can look into this specific case and provide some working solution.
