### ISSUE TITLE
Function not found due to wrong path

### ISSUE THREAD

**Issue by PascalAOMS** [callmecavs/jump.js#52]
When installing via NPM or in my case Yarn it does not find the correct file to import.

`import jump from 'jump.js'` does not find anything since there is no `index.js` installed.

Editing the path to `''jump.js/dist/jump'` does work.

Furthermore the downloaded files are all in ES5. There is no `src` folder at all.

**Comment by callmecavs** [comment]
@PascalAOMS no `index.js` is required, neither are `src` files. the downloaded files should be as they are (ES5), otherwise your build process would have to transpile your `node_modules`, which is undesirable and unmaintainable, because of the likelihood of library authors using different `babel` configs.

all the [fields in the `package.json`](https://github.com/callmecavs/jump.js/blob/master/package.json#L5-L7) that tell bundlers where to get the file from point to the `dist` folder. those `dist` files are created in the [prepublish hook](https://github.com/callmecavs/jump.js/blob/master/package.json#L24).

`npm` and `yarn` are only used to install packages - its likely a problem with your bundler config (browserify, webpack, etc) thats causing the failure to import. without seeing more of your config, its hard to say for sure, but im almost 100% positive this is related to that

**Comment by PascalAOMS** [comment]
Thank you very much for the explanation.

**Comment by callmecavs** [comment]
@PascalAOMS no problem. feel free to post your webpack/browserify config - id be happy to take a look

**Comment by PascalAOMS** [comment]
You can find my `webpack.config.js` [here](https://gist.github.com/PascalAOMS/a861a98e2381b0909c6cde56775ec3a7).

Thanks!

**Comment by callmecavs** [comment]
@PascalAOMS my guess is that something with your directory structure is throwing off webpack and preventing it from finding your `node_modules`.

the way you're aliasing `vue` looks like its because of a similar problem you had importing it. try adding a `root` to your `resolve` object, as in the following, and hopefully you wont need aliases (unless those are there for a different reason):

```javascript
resolve: {
  // point this to the root folder of your project
  // node_modules should be inside of the folder this points to
  root:  path.resolve(__dirname, './relative/path'),
  
  alias: {
    // your existing aliases might not be needed anymore
    // if jump.js works, try removing the vue alias
  }
}
```

let me know if that helps

**Comment by PascalAOMS** [comment]
I am using Webpack 2. You gave me a good tip with `root` though.

The equivalent would be
```
resolve: {
        modules: ['src', 'node_modules']
}
```
But that does not seem to work either.

**Comment by callmecavs** [comment]
@PascalAOMS im stumped. this is [my boilerplate for webpack 2](https://github.com/callmecavs/bandito), itll generate a directory for you. using that structure, everything works for me without even specifying the root directory or modules directory 🤕 

here's a link to the [webpack config](https://github.com/callmecavs/bandito/blob/master/template/webpack.config.js) (its in the `template` folder)

**Comment by PascalAOMS** [comment]
Using `const jump = require('jump.js').default` works as well.

No idea why though. Yea...
